version: '3'
services:
 node:
   image: node:8.16.0-alpine
   working_dir: "/usr/src/app"
   volumes:
    - ./:/usr/src/app
   command: sh -c "cd react-sample && yarn start"
   ports:
    - "3000:3000"
